### ISSUE TITLE
Feature Request: Add option to choose register

### ISSUE THREAD

**Issue by kevintraver** [diegoulloao/nvim-file-location#4]
- Add an option in config to set a default register
- Add a parameter in `copy_to_file` to pass in a register

Happy to help with a PR!

**Comment by diegoulloao** [comment]
What do you mean with "default register"?
I'd like to understand your idea. Please feel free to contribute with a PR 🙂

**Comment by kevintraver** [comment]
This would allow choosing which register to use when copying:

Or if unspecified, then the functionality is same as before (default to using the global system * register)

https://github.com/diegoulloao/nvim-file-location/pull/5

**Comment by kevintraver** [comment]
Passing in the register as an argument would also allow setting different keymaps to use different registers.

**Comment by diegoulloao** [comment]
I understood the feature. Nice, I didn't consider that option before.
Thanks for contributing! ❤️

**Comment by diegoulloao** [comment]
Released: https://github.com/diegoulloao/nvim-file-location/releases/tag/v1.2.0
