### ISSUE TITLE
Feature discussion: Notification to include copied text.

### ISSUE THREAD

**Issue by ian-vu** [diegoulloao/nvim-file-location#6]
Hey, just wanted to start a discussion to see if you would be open to idea of including the path copied in the notification? I think it will give good feedback if the path was seen without needing to look at the clipboard.

Possibly having a configurable flag if you think it may not be useful default functionality?

**Comment by diegoulloao** [comment]
Sorry for the delay. Yes sure, It can be included as optionally by passing a flag in the setup config.
Would you like to open a PR?

**Comment by diegoulloao** [comment]
Something like this looks good:

```lua
-- custom config
nvim_file_location.setup({
  keymap = "<leader>L",
  mode = "workdir", -- options: workdir | absolute
  add_line = true,
  add_column = false,
  default_register = "*",
  displayPath = true,
})
```
